#+TITLE:     Tomasz Skweres
#+AUTHOR:    Ezequiel Birman
#+EMAIL:     stormwatch@espiga4.com.ar
#+DATE:      2014-11-16
#+DESCRIPTION: Breve biografía
#+KEYWORDS: música, compositor, cello, cellista
#+LANGUAGE:  es
#+OPTIONS:   H:3 num:nil toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+OPTIONS:   email:t timestamp:t creator:t
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 
#+XSLT:

# Tomasz Skweres (born 1984) is a Polish composer and cellist who has
# been living in Vienna since 1997. He studied composition with Detlev
# Müller-Siemens and Chaya Czernowin as well as cello with Valentin
# Erben (the Alban Berg Quartet) and Stefan Kropfitsch at the University
# of Music and Performing Arts in Vienna.

Tomasz Skweres (nacido en 1984) es un compositor y chelista polaco
radicado en Viena desde 1997. Estudió composición con Detlev
Müller-Siemens y Chaya Czernowin; y cello con Valentin Erben (Cuarteto
Alban Berg) y Stefan Kropfitsch en la Universidad de la Musica y Artes
Escénicas de Viena.

# Composer:Works by Tomasz Skweres were performed at the Festival Wien
# Modern, Biennale Bern, Festival Klangspuren, Festival
# Komponistenmarathon (Wiener Konzerthaus), Festival "das kleine
# Symposion" at such places as Wiener Musikverein (Vienna), Gasteig
# (Munich), Stadttheater Bern (Switzerland), Wiener Konzerthaus
# (Vienna), Trafo Theater (Budapest), Theather Regensburg (Germany),
# Guangzhou Xinghai Concert Hall (China), Teatro Universitario de la
# BUAP in Puebla (México), Teatro da Reitoria in Curitiba (Brasil),
# Iglesia Presbiteriana Jan Hus de Nueva York (Estados Unidos), Alte
# Schmiede (Vienna), WUK, Echoraum and Ruprechtskirche in Vienna. His
# works were broadcasted by such radio stations as ORF/Ö1, Bayerischer
# Rundfunk, Radio Stephansdom, ABC Classic FM (Australia) and
# Frecuencia Universitaria (Mexico). As a composer he is winner of the
# International Joseph Reinl Composition Competition (2008), The
# Ernest Krenek Composition Prize (2012), the competition for the
# commissioned pieces for the International Joseph Haydn Chamber Music
# Competition (twice: 2006 - the string quartet, 2008 - the piano
# trio) as well as of the Theodor Körner Prize. He is a laureate of
# the International Composition Competition organized by the German
# Hypertension League. He is also a scholarship holder of the Thyll
# Dürr Foundation and the Czibulka Foundation and Austrian Ministry of
# Culture.

Las obras de Tomasz Skweres han sido interpretadas en el Festival Wien
Modern, Bienal de Berna, Festival Klangspuren, Festival
Komponistenmarathon (Wiener Konzerthaus), Festival /Das Kleine
Symposion/ en lugares como Wiener Musikverein (Viena), Gasteig
(Múnich), Stadttheater Bern (Suiza), Wiener Konzerthaus (Viena), Trafo
Theater (Budapest), Theather Regensburg (Alemania), Auditorio
Guangzhou Xinghai (China), Teatro Universitario de la BUAP en Puebla
(México), Teatro da Reitoria en Curitiba (Brasil), Iglesia
Presbiteriana Jan Hus de Nueva York (Estados Unidos), Alte Schmiede
(Viena), [[http://www.wuk.at/][WUK]], Echoraum y Ruprechtskirche en Viena. Sus obras fueron
transmitidas por las emisoras ORF/Ö1, Bayerischer Rundfunk, Radio
Stephansdom, ABC Classic FM (Australia) y Frecuencia Universitaria
(México). Ha ganado el Concurso Internacional de Composición Joseph
Reinl (2008), El Premio de Composición Ernst Krenek (2012), los
encargos para el Concurso International Joseph Haydn de Música de
Cámara (dos veces: 2006 --- cuarteto de cuerdas y 2008 --- trio para
piano) así como el Premio Theodor Körner. Ha sido galardonado en el
Concurso Internacional de Composición organizado por la [[http://www.hochdruckliga.de/][Sociedad
Alemana de Hipertensión]]. También es becario de la Fundación Thyll
Dürr, la Fundación Czibulka y el Ministerio de Cultura de Austria.

# The exclusive publisher of Skweres works is the Austrian Doblinger
# Musikverlag.

Las obras de Skweres son publicadas exclusivamente por [[http://www.doblinger-musikverlag.at/][Doblinger
Musikverlag]].

# Among the interpreters of his works one can mention: Apollon Musagète
# Quartett, The Meta4 String Quartet, Minetti Quartett, Quatour Voce,
# Quartetto Quiroga, Reconsil Ensemble, Ensemble Lux, Platypus Ensemble,
# Lichtental Trio, Trio Image, Trio Atanassow, Duo Kokits-Gebert,
# Ensemble Klingekunst, Duo Soufflé, Orquesta Philharmonica da UFPR,
# Ensemble Orchesterwelt, Ernst Kovacik, Xiaoming Wang, Marianna
# Oczkowska, Hibiki Oshima, Marlies Gaugl, Christoph Gaugl, Joanna
# Sachryn.

Entre los intérpretes de sus obras podemos mencionar a: Apollon
Musagète Quartett, The Meta4 String Quartet, Minetti Quartett, Quatour
Voce, Quartetto Quiroga, Reconsil Ensemble, Ensemble Lux, Platypus
Ensemble, Lichtental Trio, Trio Image, Trio Atanassow, Duo
Kokits-Gebert, Ensemble Klingekunst, Duo Soufflé, Orquesta
Philharmonica da UFPR, Ensemble Orchesterwelt, Ernst Kovacik, Xiaoming
Wang, Marianna Oczkowska, Hibiki Oshima, Marlies Gaugl, Christoph
Gaugl, Joanna Sachryn.

# Otra bio de internet también menciona al Altenberg Trio

# Cellist: As a cellist he is since 2012 solo-cellist of the
# philharmonic orchestra Regensburg in German and since 2009 member of
# RSO Wien (Radio-Symphony-Orchester Vienna) and an active interpreter
# in the field of contemporary music and chamber music. As a member of
# Hibiki Quartet he is a scholarship holder of the Herbert von Karajan
# Foundation and laureate of chamber music competitions (Gaetano Zinetti
# in Verona, Gradus ad Parnassum in Vienna and residence competition of
# the University of Music and Performing Arts in Vienna).

Como chelista, desde 2012 es solista de la Orquesta Filarmónica de
Regensburg en Alemania, desde 2009 es miembro de la /RSO Wien/
(Orquesta Sinfónica de la Radio de Viena) y un intérprete activo en el
campo de la música contemporánea y de cámara. Como integrante del
Cuarteto Hibiki es becario de la Fundación Herbert von Karajan y fue
premiado en concursos de música de cámara (Gaetano Zinetti en Verona,
/Gradus ad Parnassum/ en Viena y en el concurso para residentes de la
Universidad de Música y Artes Escénicas de Viena).
