#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline author:t
#+OPTIONS: broken-links:nil c:nil creator:nil d:(not "LOGBOOK") date:t e:t
#+OPTIONS: email:nil f:t inline:t num:nil p:nil pri:nil prop:t stat:t tags:t
#+OPTIONS: tasks:t tex:t timestamp:t title:t toc:nil todo:t |:t
#+TITLE:     Alessandro Perini
#+AUTHOR:    Ezequiel Birman
#+EMAIL:     ebirman77@gmail
#+DATE:      <2014-11-27>
#+LANGUAGE:  es,en
#+CREATOR: Emacs 26.1 (Org mode 9.1.14)
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport

#+DESCRIPTION: datos, biografía y descripción de talleres
#+KEYWORDS: música, compositor, electrónica

* Foto

* Bio de Distat Terra 2016
Nació en 1983 en Italia. Estudió composición con Luca Francesconi e
Ivan Fedele entre otros, Música Electrónica y Ciencias de la
Comunicación Musical en Italia y en Suecia.

Su producción artística abarca desde música instrumental hasta
trabajos audiovisuales y trabajos de luces con un enfoque particular
entre el sonido y la percepción visual. Sus composiciones han sido
ejecutadas en Italia y en el extranjero en festivales tales como
/Biennale di Venezia/ (Italia), Festival Futura (Francia), /Open
Spaces/ (Alemania), /Connect Festival/ (Suecia), /Procesas/
(Lituania), /UNM 2012/ (Islandia), /Moscow Forum/ (Rusia) y /Tempus
Fugit/ (Argentina) organizado por la Fundación Música AntiquaNova. En
el verano de 2014 fue Compositor en Residencia de la /Fondazione
Spinola Banna per L’Arte/ (Italia) y empezó una investigación sobre la
vibración y el sonido táctil financiada por /Kulturbryggan/,
incluyendo proyectos en Los Cursos de Verano de Darmstadt y una
residencia en /Park in Progress/ (Bélgica). En el 2015 será Artista en
Residencia de la /Fondazione Bartoli-Felter/ (Italia).

Como artista de multimedios fundó en el 2004 /Gruppo Làbun/, un trio
de investigación de multimedia galardonado con premios tales como el
/Digital Arts Award/ (Tokio 2006) y desde 2010 ha estado colaborando
con Fabio Monni como /gruppoGrupo/ un duo basado en Malmö (Suecia)
recientemente galardonado en el /Fresh Minds Festival/ y con el /Marzo
Rossi Prize/ en Italia.

Sus videos e instalaciones han sido exhibidos en festivales alrededor
del mundo y premiados en MagmArt, Premio Arte Novara, /Arrivano i
Corti, Marsciano Arte Giovani, Profezie Presenti, La Città in Lore./
Entre las exhibiciones de grupos más prestigiosos están /A.N.G.E.L.I e
tracce d'infinito/ (Lugano), /Gameplay/ (Omaha), /Flow Interrupted/
(Chicago), /La Colomba/ (Venecia) y /Art Cycle/ (Newark).

Ha estado dando cursos de producción audiovisual para las artes en el
Conservatorio de Como en Italia y de composición (curso de música
electronica) en la Academia de Música de Malmö.

* Textos de Perini para Distat Terra 2018
Recibí de SJ los textos siguientes en inglés y castellano el [2018-10-24].
** Taller
*** en                                                             :original:
    :PROPERTIES:
    :revisado: EB
    :END:
The workshop is intended for those who work with sound and/or music, and would
like to experiment with materials, sounds, spaces, objects, inventing artifacts
devoted to particular listening modes, tools to understand and listen to the
environments in which we dwell. Various tools will be available:a handy
recorder, contact microphones, super-small speakers, vibration sound devices and
basic Arduino materials. During one week, the participants will be able to work
on a project of sound art installation or performance with the aim of it
being publicly exhibited. 
*** es
El taller está destinado a aquellos que trabajan con sonido y/o música y les
gustaría experimentar con materiales, sonidos, espacios, objetos, inventando
artefactos dedicados a modos de audición particulares, herramientas para
entender y escuchar el entorno en el que habitamos. Varios materiales van a
estar disponibles: un grabador portátil, micrófonos de contácto,
micro-parlantes, dispositivos vibrantes y materiales básicos de Arduino. Durante
una semana, los participantes podrán trabajar en un proyecto de instalación
de arte sonoro o performance con el fin de una muestra pública.
*** en                                                             :original:
    :PROPERTIES:
    :revisado: EB
    :END:
Alessandro Perini was born in 1983 in Italy. He studied Composition with Luca
Francesconi and Ivan Fedele among others, Electronic Music and Science of
musical Communication in Italy and Sweden.

His very broad artistic production ranges from instrumental and electronic music
to audiovisual and light-based works, net-art, land-art, vibration-based works
and custom-built machines.

As a composer, he had his works played at festivals such as Biennale di Venezia
(Italy), Festival Futura (France), Open Spaces (Germany), Connect Festival and
New directions (Sweden), Procesas (Lithuania), UNM 2012 (Iceland), Moscow Forum
and ReMusik (Russia), Tempus Fugit and Distat Terra (Argentina). In summer 2014
he was in residence at Fondazione Spinola Banna per L'Arte (Italy).

In 2014 he started a research about vibration and tactile sound, called
touchmysound, including projects at the Darmstadt Ferienkurse and residencies at
Cittadellarte - Fondazione Pistoletto (Italy) and Park In Progress (Belgium).

Among the most significative residencies for visual artists, in 2016 he has been
awarded the Imagonirmia Prize in Chiaravalle (Milano, Italy), for a series of
projects about site-specific sound art; in 2017 he was in residence at I-Park
Foundation in Connecticut (May-June 2017); in 2018 at Fondazione Spinola Banna
per L’Arte (Italy), where he designed three machines to modify the clay found
on-site; and again in 2018 at the BIOART Society in the Finnish Lapland.

He has been teaching courses in audiovisual production for the arts at the
Conservatory of Como (Italy) and in the Composition department (electronic music
course) at the Music Academy of Malmö, as well as in workshops in Italy,
Argentina and Bolivia.

*** es
    :PROPERTIES:
    :revisado: EB
    :END:
Alessandro Perini nació en 1983 en Italia. Estudió composición con Luca
Francesconi e Ivan Fedele entre otros, Música Electrónica y Ciencias de la
Comunicación Musical en Italia y en Suecia.

Su vastísima producción artística abarca desde música instrumental y electrónica
hasta obras audiovisuales y basadas en la luz, net-art, land-art, obras basadas
en vibraciones y máquinas hechas a medida.

Sus composiciones han sido interpretadas en festivales como: Biennale di Venezia
(Italia), Festival Futura (Francia), Open Spaces (Alemania), Connect Festival y
New directions (Suecia), Procesas (Lituania), UNM 2012 (Islandia), Moscow Forum
y ReMusik (Rusia), Tempus Fugit y Distat Terra (Argentina). En el verano de 2014
fue artista en residencia de la Fondazione Spinola Banna per L'Arte (Italia).

En 2014 el empezó una investigación sobre vibración y sonido táctil llamada
touchmysound, incluyendo proyectos en los Cursos de Darmstadt y residencias en
Cittadellarte – Fondazione Pistoletto (Italia) y Park in Progress (Bélgica).

Entre las residencias más significativas para artistas visuales, en 2016 fue
galardonado con el premio Imagonirmia en Chiaravalle (Milán, Italia) por una
serie de proyectos sobre arte sonoro in situ; en 2017 participó de una
residencia en I-Park Foundation en Connecticut (Mayo-Junio 2017); en 2018 en la
Fondazione Spinola Banna per L’Arte (Italia) diseñó tres máquinas para modificar
la arcilla encontrada en el lugar; y nuevamente en 2018 en la BIOART Society en
Laponia finesa.

Ha estado dictando cursos de producción audiovisual para las artes en el
Conservatorio de Como (Italia) y en el Departamento de Composición (curso de
música electrónica) en la Academia de la Música de Malmö así como también en
Italia, Argentina y Bolivia.
