#+OPTIONS: ':t *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline author:t
#+OPTIONS: broken-links:nil c:nil creator:nil d:(not "LOGBOOK")
#+OPTIONS: date:t e:t email:nil f:t inline:t num:nil p:nil pri:nil
#+OPTIONS: prop:nil stat:t tags:t tasks:t tex:t timestamp:t title:t
#+OPTIONS: toc:nil todo:t |:t
#+TITLE: María del Rosario Castillo
#+SUBTITLE: Flautas
#+DATE: <2016-12-01>
#+AUTHOR:
#+EMAIL: ebirman77@gmail.com
#+LANGUAGE: es
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 25.1.1 (Org mode 9.0)

#+DESCRIPTION: Información y biografía
#+KEYWORDS: música, flauta

* Bio
Egresó en el año 2011 en la Universidad Nacional de Lanús con el
título de Licenciada en Música con orientación en orquesta. Realizó la
Tecnicatura de Flauta Traversa en el Conservatorio Provincial de
Música de Morón Alberto Ginastera, en la cátedra del Profesor Eduardo
Sepp, egresando en el año 2009. Sus maestros de flauta fueron Jorge de
la Vega, Patricia Da Dalt, y Martín Auza en piccolo. Realizó
masterclases con Mathias Ziegler, Celso Woltzenlogel, Nicole Esposito,
James Lyman, Michel Bellavance y Horacio Parravicini. Integró la
Orquesta del Conservatorio de Morón Alberto Ginastera, la Orquesta
Estudiantil de la Ciudad de Buenos Aires, la Banda Sinfónica de la
Facultad de Filosofía y Letras y la Orquesta de Cámara de la Radio La
Tribu. Participó del concierto sobre la música para flauta de Marta
Lambertini, y actuó como solista en la obra El imperio de la luz junto
a la Orquesta de Cámara de la UNLa. En 2013 fue invitada a participar
del ciclo de conciertos de música contemporánea Tempus Fugit y del
ciclo Ars Nova realizado en Choele Choel. Actualmente cursa la
Diplomatura Superior de Música Contemporánea del Conservatorio
Superior de Música Manuel de Falla, en la cátedra de Interpretación a
cargo de Patricia Da Dalt, y se perfecciona en instrumento con la
flautista María Cecilia Muñoz. Desde el 2010 hasta la fecha, integra
como primera flauta la Orquesta de Cámara de la Universidad Nacional
de Lanús y desde el 2013 participa del ensamble Voxes Contemporánea.
