#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline author:t
#+OPTIONS: broken-links:nil c:nil creator:nil d:(not "LOGBOOK") date:t e:t
#+OPTIONS: email:nil f:t inline:t num:nil p:nil pri:nil prop:nil stat:t tags:t
#+OPTIONS: tasks:t tex:t timestamp:t title:t toc:nil todo:t |:t
#+TITLE: Ina Morales
#+SUBTITLE: Dramaturga
#+DATE: <2018-10-23 mar>
#+AUTHOR: Ezequiel Birman
#+EMAIL: ebirman77@gmail.com
#+LANGUAGE: es,en
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 26.1 (Org mode 9.1.14)

#+DESCRIPTION: biografía
#+KEYWORDS: teatro

# Texto enviado por Sofía Jallinsky para traducir
* CV Abreviado
** es
#+BEGIN_SRC translate :src es :dest en :exports none
Ina Morales es directora, actriz y docente. Desde el año 2012 se dedica a la
investigación y creación de poéticas escénicas con objetos y materiales.
Egresada de la Especialización en Teatro de Objetos, Interactividad y Nuevos
Medios de la Universidad Nacional de las Artes (U.N.A) y del Profesorado en Arte
Dramático del Instituto Nacional Superior de las Artes (I.N.S.A). Actualmente
vive y desarrolla su actividad artística en Buenos Aires. Su obra a participado
del Ciclo La Música en Diálogo con otras Artes en el espacio de arte de la
Fundación OSDE. Ciclo Trama de Objetos organizado por la U.N.A bajo la curaduría
de Ana Alvarado, 1°Festival Escena Doméstica sede Buenos Aires, entre otros. Fue
seleccionada para participar del festival Fiesta Provincial de Teatro C.A.B.A
2017 organizado por I.N.T. Fue becaría del Instituto Nacional del Teatro. Ha
realizado funciones en diferentes teatros de Capital Federal, Bahía Blanca, Río
Negro y Neuquén.
#+END_SRC
** en
#+results:
Ina Morales is a theatre director, actor and teacher. Since 2012 she has delved
into the research and creation of scenic poetry with objects and materials. Mrs.
Morales did earn a degree in Theater of Objects, Interactivity and New Media
from the /Universidad Nacional de Las Artes/ and from the Dramatic Art
Professorship of the /Instituto Nacional Superior de Las Artes/. She currently
lives and performs in Buenos Aires. Her work featured at the festival /Ciclo La
Música en Diálogo Con Las Otras Artes/ by /Fundación OSDE/; /Ciclo Trama de
Objetos/ at U. N. A. under the curatorship of Ana Alvarado and /Primer Festival
Escena Domestica/ in Buenos Aires, among others. She was selected to work at the
/Festival Provincial de Teatro C. A.B .A  2017/ organized by I. N.T. She was a
fellow of the /Instituto Nacional del Teatro/. Ina Morales has performed at
various theaters in Buenos Aires, Bahía Blanca, Río Negro and Neuquén.
