#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline author:t
#+OPTIONS: broken-links:nil c:nil creator:nil d:(not "LOGBOOK") date:t e:t
#+OPTIONS: email:nil f:t inline:t num:nil p:nil pri:nil prop:nil stat:t tags:t
#+OPTIONS: tasks:t tex:t timestamp:t title:t toc:nil todo:t |:t
#+TITLE: Lorena Faccio
#+SUBTITLE: Fotógrafa
#+DATE: <2018-10-23 mar>
#+AUTHOR: Ezequiel Birman
#+EMAIL: ebirman77@gmail.com
#+LANGUAGE: es,en
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 26.1 (Org mode 9.1.14)

#+DESCRIPTION: biografía
#+KEYWORDS: plástica

* Vita brevis 

:PROPERTIES:
:Nacionalidad: Argentina
:Ciudad: Buenos Aires
:Fecha: 1974
:END:

# Texto original español.
* es
Egresa de la Escuela Nacional de Bellas Artes Prilidiano Pueyrredón como
Profesora Nacional de Escultura y Pintura. Asiste al Workshop de Iluminación
Fotográfica con Gustavo Demaría. Cursa el Taller de Video Analógico con Javier
Plano. Realiza entrenamiento en Danza Contemporánea con Fabiana Capriotti.
Asiste al Taller sobre pensamiento Queer, dictado por Moira Pérez, Dra. en
filosofía (UBA). Estudia Fotografía Estenopeica en el Museo Fotográfico Simik.
Cursa el Taller de Video, coordinado por Gustavo Galuppo, Hernán Khourian y
Andrés Denegri en el Espacio Fundación Telefónica. Participa del taller sobre
Redacción de Statement, dictado por Kekena Corvalán. Asiste al taller teórico
práctico sobre Arte, Ciencia y Tecnología, a cargo de Mariano Sardón y Rodrigo
Alonso en el Espacio Fundación Telefónica. Cursa el Taller de Fotografía con
Gabriel Valansi. Forma parte del taller de Fotografía y Revelado con Eduardo
Gil. Expone en Buenos Aires, Caracas, París, Niza, Bergamo, Verona, Milán,
Bologna, Nápoles, Caserta, Brescia, Bari y Lecce. Sus obras forman parte de
varias colecciones privadas y públicas en Argentina, Italia, Hungría y Francia.
Vive y trabaja en Buenos Aires.

* en
Lorena Faccio graduated from the National School of Fine Arts Prilidiano
Pueyrredón with the degree of /Profesora Nacional de Escultura y Pintura/.
Then Attended a photographic lighting workshop under Gustavo Demaría, and an
analog video Workshop under Javier Plano. She trained in Contemporary Dance with
Fabiana Capriotti; attended a Queer Thinking Workshop, given by Moira Pérez,
Ph.D. in Philosophy (U B A). Faccio studied pinhole photography at the Simik
Photographic Museum. Attended a video workshop under Gustavo Galuppo, Hernán
Khourian and Andrés Denegri at /Espacio Fundación Telefónica/. Took a workshop
on Statement Writing, dictated by Kekena Corvalán; attended the
Practical-Theoretical Workshop on Art, Science and Technology, under Mariano
Sardón and Rodrigo Alonso at Espacio Fundación Telefónica; took the Photography
Workshop by Gabriel Valansi. She is a member of a photography and development
workshop with Eduardo Gil; She had exhibits in Buenos Aires, Caracas, Paris,
Nice, Bergamo, Verona, Milan, Bologna, Naples, Caserta, Brescia, Bari and Lecce.
Her works are part of several private and public collections in Argentina,
Italy, Hungary and France. She lives and works in Buenos Aires.
