#+TITLE:     Theresia Schmidinger
#+AUTHOR:    Ezequiel Birman
#+EMAIL:     stormwatch@espiga4.com.ar
#+DATE:      2014-11-07
#+DESCRIPTION: Breve biografía
#+KEYWORDS: música, flauta, clarinete, duo
#+LANGUAGE:  es
#+OPTIONS:   H:3 num:nil toc:nil \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+OPTIONS:   email:t timestamp:t creator:t
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 
#+XSLT:

# Theresia Schmidinger grew up in  Tyrol/Austria and is currently living
# as a freelance musician in Vienna.

Theresia Schmidinger creció en Tirol, Austria y actualmente vive como
música /freelance/ en Viena.

# She studied clarinet with Gerald Pachinger, Wolfgang Klinser and
# Walter Seebacher. Also, she studied chamber music with Johannes Meissl
# and Gottfried Pokorny at the University for Music, Vienna. She
# furthered her studies at academies such as the International Ensemble
# Modern Academy Schwaz, Internationale Ferienkurse für Neue Musik
# Darmstadt, Impuls International Ensemble Academy and the Summer
# Academy Mozarteum Salzburg. She has also undertaken masterclasses with
# Ernesto Molinari, Norbert Täubl, Hansjörg Schellenberger, Michel
# Letiec, Aurel Nicolet, Heinz Holliger, Rupert Fankhauser, Mate Bekavac
# and Alexander Neubauer.

Estudió clarinete con Gerald Pachinger, Wolfgang Klinser y Walter
Seebacher. También estudió música de cámara con Johannes Meissl y
Gottfried Pokorny en la [[http://www.mdw.ac.at][Universidad de la Música de Viena]]. Se
perfeccionó en academias como la [[http://www.internationale-em-akademie.de/][Academia Internacional Ensemble
Modern]] en Schwaz, los [[http://www.internationales-musikinstitut.de/en/summer-course][Cursos de Verano de Darmstadt]], la [[http://www.impuls.cc/][Impuls
International Ensemble Academy]] y la [[http://www.moz.ac.at/de/kunst/soak/index.php][Academia de Verano del Mozarteum
de Salzburgo]]. También a asistido a clases magistrales con Ernesto
Molinari, Norbert Täubl, Hansjörg Schellenberger, Michel Letiec, Aurel
Nicolet, Heinz Holliger, Rupert Fankhauser, Mate Bekavac y Alexander
Neubauer.

# Beside being a well sought after chamber musician she also performs in
# various orchestras such as Vienna Symphony Orchestra, Vienna Chamber
# Philharmony, Vienna Chamber Orchestra, Chamber Opera Vienna and
# others.

Además de ser una intérprete de música de cámara muy solicitada,
también participa en varias orquestas como la Orquesta Sinfónica de
Viena, La Ópera de Cámara de Viena y otras.

# A particular interest of hers lies in contemporary music, dialogue
# with composers and in exploring the sound possibilities of both
# clarinet and bassclarinet. Besides her intense work with "Duo
# Soufflé", she has premiered serveral works as a soloist, and performed
# in various ensembles at festivals such as Wien Modern and Klangspuren
# Schwaz (Austria), Bienale Música Hoje (Brazil), Proyecto de
# Intercambio Mexico-Austria and at the Austrian Cultural Forum in New
# York. She is founding member of the Ensemble Platypus, and has
# performed with Ensemble Reconsil, Ensemble Phace, "Kapelle für Neue
# Musik Windkraft" and at the Ferienkurse Darmstadt.

Se interesa particularmente por la música contemporánea, por el
diálogo con compositores y por la exploración de las posibilidades
sonoras del clarinete y del clarinete bajo. Además de su intenso
trabajo en /Duo Soufflé/, ha estrenado muchas obras solistas, y tocó
con varios ensambles en festivales como /[[http://www.wienmodern.at/][Wien Modern]]/ y /[[http://www.klangspuren.at/klangspuren-schwaz][Klangspuren
Schwaz]]/ (Austria), /[[/http://bienalmusicahoje.com/][Bienale Música Hoje]]/ (Brasil), Proyecto de
Intercambio Mexico-Austria y en el [[http://www.acfny.org/home/][Foro Cultural Austríaco en New
York]]. Es miembro fundadora del [[http://platypusensemble.wordpress.com/][Ensemble Platypus]], y ha tocado con el
[[http://www.ensemblereconsil.com/][Ensemble Reconsil]], el [[http://phace.at][Ensemble Phace]], el /[[http://windkraftmusic.com/][Kapelle für Neue Musik
Windkraft]]/ y en los [[http://www.internationales-musikinstitut.de/en/summer-course][Cursos de Verano de Darmstadt]].

# Theresia Schmidinger also works as a music teacher
# (Niederösterreichisches Musikschulwerk). She is involved in various
# projects such as music theater for children, tutoring a youth
# orchestra (Brazil), and the "school project for composition" with
# Ensemble Platypus.

Theresia Schmidinger trabaja también como profesora de música
(/Niederösterreichisches Musikschulwerk/). Está involucrada en varios
proyectos como la música de teatro para niños, apadrinar una orquesta
de músicos jóvenes (Brasil) y el Proyecto Escolar de Composición con
el [[http://platypusensemble.wordpress.com/][Ensemble Platypus]].
