#+OPTIONS: ':t *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline author:t
#+OPTIONS: broken-links:nil c:nil creator:nil d:(not "LOGBOOK")
#+OPTIONS: date:t e:t email:nil f:t inline:t num:nil p:nil pri:nil
#+OPTIONS: prop:nil stat:t tags:t tasks:t tex:t timestamp:t title:t
#+OPTIONS: toc:nil todo:t |:t
#+TITLE: Yui Iwata
#+SUBTITLE: Violín
#+DATE: <2016-11-28 lun>
#+AUTHOR:
#+EMAIL: ebirman77@gmail.com
#+LANGUAGE: es
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 25.1.1 (Org mode 9.0)

#+DESCRIPTION: Información y biografía
#+KEYWORDS: música, violín

* Bio
Nació en Tokio y empezó a estudiar violín a la edad de cinco años.
Iwata completó sus estudios musicales (bachelor y master degree) con
“altas distinciones” en el Tokyo Ongaku Daigaku (Colegio de Música de
Tokio) estudiando con el Prof. Yasuko Otani y ganando también el 3er
Premio en la Competencia para Violín realizada por la misma
Institución.

Desde 2013 comenzó a trabajar en Alemania como violinista de orquesta
en el Teatro Estatal de Kassel. Desde ese entonces vive en la ciudad
de Regensburg (Alemania) donde trabaja en la sección primera de
violines de la Orquesta del Teatro de Regensburg.

Iwata es una activa interprete en múltiples proyectos de música de
cámara con los cuales ha tocado en diversas salas de Europa y Japón.

Desde el 2016 es miembro del Cuarteto Skweres, junto a Hibiki Oshima
(solista de la segunda sección de violines en la Staatsoper Hamburg),
Marie Yamanaka (solista adjunto de la Staatsoper Kiel) y Tomasz
Skweres (violonchelista principal en la Orquesta del Teatro de
Regensburg, compositor).

Ha interpretado el Concierto para violín y orquesta en Re mayor de
W. A. Mozart con la Südwestdeutsche Philharmonie Konstanz y el 1er
Concierto para violín y orquesta de Philip Glass junto a la Orquesta
Filarmónica de Regensburg.
