#+TITLE: Richard Craig
#+SUBTITLE: flautas
# #+EMAIL: contacto@fundacionmusicaantiquanova
#+DATE: <2018-11-15>
#+LANGUAGE: es
#+DESCRIPTION: biografía 
#+KEYWORDS: música, flauta

#+INCLUDE: "datos.org"

* default                                                            :ignore:
{{{property(bio_photo,*Datos)}}}

Richard Craig estudió flauta en la Academia Escocesa Real de Música y Arte
Dramático (actualmente el Consevatorio Real de Escocia) con Sheena Gordon y
luego con Richard Blake. Tras graduarse con honores continuó sus estudios en el
Conservatorio de Estrasburgo, Francia, con Mario Caroli.

Ha tocado con grupos como ELISION, Musikfabrik, Klangforum
Wien, el Coro de la Radio de Estonia, la Orquesta RTÉ y Das Experimentalstudio
Ensemble, que lo han llevado a festivales internacionales como Maerzmusik
Berlin, Wittener Tage für Neue Musik, la Bienal de Venecia, el Festival de
Música Contemporánea de Huddersfield, el Festival de Otoño de París y el Lincoln
Center Festival de Nueva York. Igualmente activo como solista, Craig ha dado
recitales en todo el mundo interpretando obras nuevas y presentando sus
colaboraciones, trabajando junto a músicos como Rohan de Saram y Roberto
Fabbriciani. El interés de Craig por la música contemporánea se centra en el
desarrollo de un nuevo repertorio para flauta y para ello realiza encargos tanto
a compositores establecidos como a la generación más joven de artistas. Como
músico de cámara, ha actuado con el Distractfold Ensemble, ganadores del premio
Kranisteiner 2014, y es miembro del conjunto español SMASH.

Como profesor, ha impartido clases magistrales y seminarios en la Universidad de
Maryland en Baltimore, la Universidad de Huddersfield, la Universidad de St
Andrews, la Universidad de Aberdeen, el Royal Northern College of Music, el
Royal Scottish Conservatoire, la Universidad Lawrence de Wisconsin y fue
nombrado intérprete en residencia en la Universidad de Aberdeen, 2009–11. De
2012 a 2014 fue profesor visitante en el curso de posgrado de rendimiento en la
Universidad de Huddersfield y además fue nombrado Investigador Honorario en la
misma universidad 2014–2019. En octubre de 2015 se convirtió en titular de la
Cátedra de Interpretación de la Universidad de Bangor, Gales.

Ha grabado para la BBC, WDR Colonia, Radiodifusión pública de Finlandia (YLE),
Radio Francia, Radio Nacional de España, Radio Sueca, ARTE, Radiodifusión
estatal de Islandia (RÚV), [[https://de.schott-music.com/wergo/][Wergo]] y Another Timbre. Su disco debut como solista
INWARD fue lanzado en el sello Métier en 2011 con gran éxito por parte de la
crítica. INWARD ha sido desde entonces el único disco de música clásica nominado
para el Álbum Escocés del Año 2012. Actualmente está preparando un segundo disco
con Métier para su lanzamiento en 2017. Este incluirá los primeros registros de
obras a estrenar de Esaias Järnegard, Richard Barrett, John Croft, Brice Pauset,
Evan Johnson y Fabrice Fitch, con el apoyo de Creative Scotland. Junto a sus
tres discos monográficos, ha participado en grabaciones con los ensambles
MusikFabrik, Octandre, SMASH, Distractfold y Grizzana. Como improvisador ha
tocado con Barry Guy, la Glasgow Improvisers Orchestra y ha grabado con el grupo
de Evan Parker.

Como intérprete/compositor lanzó el disco AMP/AL en colaboración con Rodrigo
Constanzo y la artista Angela Guyton en 2013.

{{{property(website,*Datos)}}}
