#+TITLE: Francesco Dillon
#+SUBTITLE: Violoncello
#+DATE: <2016-11-17 jue>
#+AUTHOR: Francesco Dillon
#+EMAIL: contacto@fundacionmusicaantiquanova.org.ar
#+LANGUAGE: en
#+DESCRIPTION: Biography
#+KEYWORDS: music, violoncello

* TODO default                                    :actualizar:revisar:ignore:
# De la web oficial

Francesco Dillon (b.Turin, 1973) already has a brilliant international career to
his credit, characterised by the originality and variety of the repertoire that
he has embraced. As a soloist he has performed on such prestigious concert
stages as the Konzerthaus in Vienna, the Muziekgebouw in Amsterdam, the Berlin
Philharmonie, the Herkulessaal of Munich, the Laeiszhalle in Hamburg, the Jordan
Hall in Boston and the Colon Theatre of Buenos Aires, with such orchestras as
the Italian National Radio Orchestra (RAI), the Southwest Radio Symphony
Orchestra of Stuttgart, the Radio Symphony Orchestra of Vienna, the Orchestra of
the Colon Theatre, Ensemble Resonanz, Oulu Sinfonia Finland, and the Tuscany
Regional Orchestra (ORT). Most recently he made an acclaimed debut with the
Philharmonic Orchestra of La Scala, Milan, conducted by Susanna Mallki.

As a member of the internationally acclaimed group AlterEgo and as a soloist, he
is invited to play in all the major contemporary music festivals. He regularly
plays chamber music with partners such as I.Arditti, G. Carmignola, P.
Farulli, V. Hagen, A. Lonquich, E. Pace, R. Schmidt, S. Scodanibbio. He won
several competitions and with the quartet prizes at Prague spring (1st prize
1998), ARD Munich, Bordeaux. His performances are broadcasted by BBC, ARD, Radio
France, ORF, ABC, RAI, a.o.

In 1993 he was one of the founders of the Quartetto Prometeo, a chamber group of
international acclaim and winner of numerous prizes (Prague Spring, ARD Munich,
Bordeaux) and recently honoured with the Leone d’Argento award of the Biennale
Musica of Venice. Dillon is also a stable member of the Alter Ego ensemble which
is regularly invited to the major contemporary music festivals around the world.
His passion for chamber music has led to performances with musicians such as
Irvine Arditti, Mario Brunello, Giuliano Carmignola, Piero Farulli, David
Geringas, Veronika Hagen, Alexander Lonquich, Enrico Pace, Jean-Guihen Queyras.

The profound interest in contemporary music which he has always cultivated has
led to solid collaborations with the major composers of our time: Gavin Bryars,
Ivan Fedele, Luca Francesconi, Stefano Gervasoni, Philip Glass, Vinko Globokar,
Sofija Gubaidulina, Jonathan Harvey, Toshio Hosokawa, Giya Kancheli, Alexander
Knaifel, Helmut Lachenmann, David Lang, Alvin Lucier, Arvo Pärt, Henri Pousseur,
Steve Reich, Fausto Romitelli, Kaija Saariaho, Salvatore Sciarrino and with cult
experimental musicians such as Matmos, and Pansonic, William Basinsky and John
Zorn.

Dillon's performances have been transmitted by such important broadcasters as
the BBC, RAI, ARD, Radio France, ORF, the Australian Broadcasting Corporation
and WDR. He has recorded for the ECM label, as well as Kairos, Ricordi,
Stradivarius, Die Schachtel and Touch. He recently recorded for the first time,
Variations by Salvatore Sciarrino which received the Diapason d’0r prize, and
Ballatta by Giacinto Scelsi, both with the Italian National Radio Orchestra
(RAI). As a duo with the pianist Emanuele Torquati, he has brought out three CDs
of rare music of Schumann and the complete works for cello by Franz Liszt for
Brilliant Classics. Along with his concert activity there have been teaching
experiences in institutions such as the School of Music of Fiesole, the
Tchaikovsky Conservatory of Moscow, the Pacific University in California,
Untref-Buenos Aires, Manchester University. From 2010 he has been artistic
director of the season of contemporary music Music@villaromana in Florence.
