#+TITLE: Francesco Dillon
#+SUBTITLE: Violonchelo
#+DATE: <2016-11-17 jue>
#+AUTHOR: Francesco Dillon
#+EMAIL: contacto@fundacionmusicaantiquanova.org.ar
#+LANGUAGE: es
#+DESCRIPTION: Biografía
#+KEYWORDS: música, violoncello

* Bio
# De la web oficial
Francesco Dillon (Turín, 1973) ya cuenta con una brillante carrera internacional
en su haber, que se caracteriza por la originalidad y la variedad del repertorio
que ha abrazado. Como solista ha actuado en escenarios tan prestigiosos como el
Konzerthaus de Viena, el Muziekgebouw de Amsterdam, la Filarmónica de Berlín, la
Herkulessaal de Munich, el Laeiszhalle de Hamburgo, el Salón Jordan en Boston y
el Teatro Colón de Buenos Aires, con orquestas como la Orquesta de la RAI, la
Orquesta Sinfónica de la SWR de Stuttgart, la Orquesta Sinfónica de la Radio de
Viena, la Orquesta del Teatro Colón, Ensemble Resonanz, Oulu Sinfonia Finlandia,
y la Orquesta regional de Toscana (ORT). Más recientemente tuvo un aclamado
debut con la Filarmónica de La Scala de Milán, dirigida por Susanna Mallki.

Estudió con Andrea Nannoni, perfeccionandose luego con Amadeo Baldovino, Mario
Brunello y David Geringas, atendiendo a las clases magistrales de Mstislav
Rostropovich, Anner Bylsma y Miklós Perényi. Fue alumno de composición de
Salvatore Sciarrino.

En 1993 fundo con sus compañeros el Cuarteto Prometeo, un grupo de cámara
reconocido internacionalmente y ganador de numerosos premios (Primavera de
Praga, ARD de Munich, Burdeos) y, recientemente galardonado con el León de Plata
en la Bienal de Música de Venecia. Dillon es también un miembro estable del
conjunto Alter Ego que está invitado regularmente a los principales festivales
de música contemporánea de todo el mundo. Su pasión por la música de cámara ha
dado lugar a actuaciones con músicos como Irvine Arditti, Mario Brunello,
Giuliano Carmignola, Piero Farulli, David Geringas, Veronika Hagen, Alexander
Lonquich, Enrico Pace y Jean-Guihen Queyras.

El profundo interés por la música contemporánea que ha cultivado desde siempre,
ha dado lugar a muchas colaboraciones con los principales compositores de
nuestro tiempo: Gavin Bryars, Ivan Fedele, Luca Francesconi, Stefano Gervasoni,
Philip Glass, Vinko Globokar, Sofija Gubaidulina, Jonathan Harvey, Toshio
Hosokawa , Giya Kancheli, Alexander Knaifel, Helmut Lachenmann, David Lang,
Alvin Lucier, Arvo Pärt, Henri Pousseur, Steve Reich, Fausto Romitelli, Kaija
Saariaho, Salvatore Sciarrino y con músicos experimentales de culto como Matmos,
Pansonic, William Basinsky y John Zorn.

Las actuaciones de Dillon se han transmitido por radiodifusoras tan importantes
como la BBC, la RAI, la ARD, Radio France, la ORF, la Australian Broadcasting
Corporation y la WDR. Ha grabado para el sello ECM, así como Kairos, Ricordi,
Stradivarius, Die Schachtel y Touch. Grabó por primera vez un disco con las
/Variazioni/ de Salvatore Sciarrino que fue galardonado con el /Diapason d'Or/,
y la /Ballata/ de Giacinto Scelsi, ambos registros con la orquesta de la RAI. A
dúo con el pianista Emanuele Torquati grabó tres discos: un disco compacto doble
de rarezas de Schumann y las obras completas de Franz Liszt para violonchelo
para el sello Brilliant Classics. Junto a su actividad de conciertos fue docente
en instituciones como la Escuela de Música de Fiesole, el Conservatorio
Tchaikovsky de Moscú, la Universidad del Pacífico en California, la UNTREF y la
Universidad de Manchester. Desde 2010 ha sido director artístico del ciclo de
música contemporánea Music@Villaromana en Florencia.
