#+TITLE: Walter Ifrim
#+SUBTITLE: clarinet
#+AUTHOR: Walter Ifrim
#+EMAIL: contacto@fundacionmusicaantiquanova
#+DATE: <2018-11-11>
#+LANGUAGE: en
#+CREATOR: Emacs 26.1 (Org mode 9.1.14)
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport

#+OPTIONS: html-link-use-abs-url:nil html-postamble:nil html-preamble:nil
#+OPTIONS: html-scripts:t html-style:t html5-fancy:t tex:t
#+HTML_DOCTYPE: html5
#+HTML_CONTAINER: div
#+DESCRIPTION: biography 
#+KEYWORDS: music, flute
#+HTML_LINK_HOME:
#+HTML_LINK_UP:
#+HTML_MATHJAX:
#+HTML_HEAD:
#+HTML_HEAD_EXTRA:
#+INFOJS_OPT:
#+CREATOR: <a href="https://www.gnu.org/software/emacs/">Emacs</a> 26.1 (<a href="https://orgmode.org">Org</a> mode 9.1.14)
#+LATEX_HEADER:

#+INCLUDE: "datos.org"

* default                                                            :ignore:
{{{property(bio_photo,*Datos)}}}

# http://unfilrouge.eu/en/mitwirkende.html
Walter Ifrim was born in Romania and studied clarinet in the College of music,
Bucharest. Since 1983 he lives in Germany and is active as a soloist, chamber
musician and teacher in germany as well as abroad. As a founding member of the
ensemble Aventure (1986) and the " trio RUGA " (2001) he has participated in
different famous concerts and festivals in Germany, Donaueschingen, Witten,
Berlin, München, Köln and Stuttgart among others as well as abroad in Argentina,
France, Switzerland, Italy, Spain, Austria, Slovenia, Czechia, Mexico, Brazil,
Uruguay, China, Japan, Ecuador, Romania. Celebrated contemporary composers like
Nicolaus A. Huber, Rolf Riehm, Uros Rojko, Wolfgang Motz, Francesco M. Paradiso,
Max E. Cellar, Mariano Etkin, Coriún Aharonian, Mesias Maiguashca, Roland
Breitenfeld, Donoung Lee dedicated him their works. Numerous CD and radio
broadcastings document his active musical activity as a soloist and chamber
musician in the classic to romantic repertoire as well as in the newest
avant-garde music.

{{{property(website,*Datos)}}}
