#+TITLE: Walter Ifrim
#+SUBTITLE: clarinete
#+AUTHOR: Walter Ifrim
#+EMAIL: contacto@fundacionmusicaantiquanova
#+DATE: <2018-11-11>
#+LANGUAGE: es
#+CREATOR: Emacs 26.1 (Org mode 9.1.14)
#+DESCRIPTION: biography 
#+KEYWORDS: music, clarinet

#+INCLUDE: "datos.org"

* default                                                            :ignore:
{{{property(bio_photo,*Datos)}}}

#+BEGIN_SRC translate :src de :dest es :exports none
  Walter Ifrim wurde in Rumänien geboren und studierte Klarinette an der
  Musikhochschule in Bukarest. Seit 1983 lebt er in Deutschland und ist als
  Solist, Kammermusiker und Pädagoge im In- und Ausland tätig. Als
  Gründungsmitglied des Ensemble Aventure (1986) und des "trio RUGA" (2001) hat er
  an verschiedenen renommierten Festivals und Konzertreihen in Deutschland
  (Donaueschingen, Witten, Berlin, München, Köln, Stuttgart u.a.) und im Ausland
  (Argentinien, Frankreich, Schweiz, Italien, Spanien, Österreich, Slowenien,
  Tschechien, Mexiko, Brasilien, Uruguay, China, Japan, Ecuador, Rumänien)
  teilgenommen. Namhafte zeitgenössische Komponisten wie Nicolaus A. Huber, Rolf
  Riehm, Uros Rojko, Wolfgang Motz, Francesco M. Paradiso, Max. E. Keller, Mariano
  Etkin, Coriún Aharonian, Mesias Maiguashca, Roland Breitenfeld, Donoung Lee und
  andere widmeten ihm ihre Werke. Zahlreiche CD- und Rundfunkaufnahmen
  dokumentieren seine rege musikalische Tätigkeit als Solist und Kammermusiker im
  Bereich der klassisch-romantischen sowie der neuesten avantgardistischen Musik.
#+END_SRC

Walter Ifrim nació en Rumania y estudió clarinete en la Academia de Música de
Bucarest. Vive en Alemania desde 1983 y trabaja como solista, músico de cámara y
educador en Alemania y en el extranjero. Como miembro fundador del Ensemble
Aventure (1986) y el /trío RUGA/ (2001), se ha presentado en varios festivales y
ciclos de conciertos de renombre en Alemania (Donaueschingen, Witten, Berlín,
Munich, Colonia, Stuttgart, etc.) y en el extranjero (Argentina, Francia,
Suiza). , Italia, España, Austria, Eslovenia, República Checa, México, Brasil,
Uruguay, China, Japón, Ecuador, Rumania). Renombrados compositores
contemporáneos como Nicolaus A. Huber, Rolf Riehm, Uros Rojko, Wolfgang Motz,
Francesco M. Paradiso, Max E. Keller, Mariano Etkin, Coriún Aharonian, Mesias
Maiguashca, Roland Breitenfeld, Donoung Lee y otros han escrito obras para él.
Numerosas grabaciones de CD y radio documentan su nutrida actividad musical como
solista y músico de cámara en el campo de la música clásica/romántica, así como
la última música de vanguardia.
