#+TITLE: Walter Ifrim
#+SUBTITLE: clarinet
#+AUTHOR: Walter Ifrim
#+EMAIL: contacto@fundacionmusicaantiquanova
#+DATE: <2018-11-11>
#+LANGUAGE: en
#+DESCRIPTION: biography 
#+KEYWORDS: music, clarinet

#+INCLUDE: "datos.org"

* default                                                            :ignore:
{{{property(bio_photo,*Datos)}}}

# http://unfilrouge.eu/en/mitwirkende.html
Walter Ifrim was born in Romania and studied clarinet at the Bucharest Music
Conservatory. Since 1983 he lives in Germany and is active as a soloist, chamber
musician and teacher in germany as well as abroad. As a founding member of the
ensemble Aventure (1986) and the Trio RUGA (2001), he has participated in
different famous concerts and festivals in Germany like Donaueschingen, Witten,
Berlin, Munich, Cologne and Stuttgart among others as well as abroad in
Argentina, France, Switzerland, Italy, Spain, Austria, Slovenia, Czechia,
Mexico, Brazil, Uruguay, China, Japan, Ecuador and Romania. Celebrated
contemporary composers like Nicolaus A. Huber, Rolf Riehm, Uros Rojko, Wolfgang
Motz, Francesco M. Paradiso, Max E. Cellar, Mariano Etkin, Coriún Aharonian,
Mesías Maiguashca, Roland Breitenfeld, Donoung Lee dedicated him their works.
Numerous CD and radio broadcastings document his active musical activity as a
soloist and chamber musician in the classic to romantic repertoire as well as in
the newest avant-garde music.
